### ISSUE TITLE
dataset_csv_sig -> datasets_csv_sig

### ISSUE THREAD

**Issue by JianJuly** [mahmoodlab/MCAT#3]
https://github.com/mahmoodlab/MCAT/blob/4fae60a1a1229ccd7a2cd1f43e0011636099847d/datasets/dataset_survival.py#L126

**Comment by Richarizardd** [comment]
Oh yes - good catch.

**Comment by JianJuly** [comment]
> 

Also, i am not able to find the place where to set `args.inst_loss` in `main.py`

**Comment by Richarizardd** [comment]
Hi @JianJuly - sorry for the delay. The `args.inst_loss` was an argument used in CLAM, which I may have just copied over in building on top of that scaffold. Let me update the repository.

**Comment by ljhOfGithub** [comment]
> Hi @JianJuly - sorry for the delay. The `args.inst_loss` was an argument used in CLAM, which I may have just copied over in building on top of that scaffold. Let me update the repository.嗨-抱歉耽搁了。 `args.inst_loss` 是CLAM中使用的一个参数，我可能刚刚在脚手架上复制了这个参数。让我更新仓库。

Hello!You haven't update the repo,and I find many bugs still.Could you please update the repo?
