### ISSUE TITLE
Question about 'fast_cluster_ids.pkl'

### ISSUE THREAD

**Issue by Houjiaxin123** [mahmoodlab/MCAT#4]
Thank you for sharing your code！I‘m interested in your research, it gives me a lot of inspiration.
While trying to run the code, I'm confused about the file 'fast_cluster_ids.pkl' in dataset_survival.py. I can't find a description about it. 
Could you please tell me what this file contains? Thank you very much!

**Comment by Richarizardd** [comment]
HI @Houjiaxin123 - Thank you for taking interest in the codebase! The "fast_cluster_ids.pkl" was used for running the DeepAttnMISL baseline, in which we precompute all the cluster assignments for each patch. I will update the code soon so that you can run the code w/o the "fast_cluster_ids.pkl" for each file.

**Comment by Houjiaxin123** [comment]
OK, I see. Thanks a lot!

**Comment by SuooL** [comment]
> HI @Houjiaxin123 - Thank you for taking interest in the codebase! The "fast_cluster_ids.pkl" was used for running the DeepAttnMISL baseline, in which we precompute all the cluster assignments for each patch. I will update the code soon so that you can run the code w/o the "fast_cluster_ids.pkl" for each file.

Have you updated the code? I still have this problem on my side.

**Comment by lmxmercy** [comment]
> Thank you for sharing your code！I‘m interested in your research, it gives me a lot of inspiration. While trying to run the code, I'm confused about the file 'fast_cluster_ids.pkl' in dataset_survival.py. I can't find a description about it. Could you please tell me what this file contains? Thank you very much!

Have you solve this problem? Thx!
