### ISSUE TITLE
Question about 'fast_cluster_ids.pkl'

### ISSUE THREAD

**Issue by SuooL** [mahmoodlab/MCAT#6]
Have you updated the code? I still have this problem on my side. Which have mentioned in #4

**Comment by ljhOfGithub** [comment]
Hello!Do you solve the problem?I notice that in Patch-GCN/dataset/dataset_survival.py:
https://github.com/mahmoodlab/Patch-GCN/blob/00207f03e541f1b26ef2bf6103502b30d9422700/datasets/dataset_survival.py#L287-L289
if os.path.isfile(os.path.join(data_dir, 'fast_cluster_ids.pkl')):
            with open(os.path.join(data_dir, 'fast_cluster_ids.pkl'), 'rb') as handle:
                self.fname2ids = pickle.load(handle)
But in the repo,the 'if' is deleted.
